spring.application.name=railsy-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/railsy
spring.datasource.username=macbook
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080